### ISSUE TITLE
About the UKBB dataset

### ISSUE THREAD

**Issue by ztt0821** [siyi-wind/TIP#1]
Hi, nice work! I am applying for the UKBB dataset now. I have applied the account. Could you share the category ID or other dataset information for me? Because I don't know which dataset I need to apply and download. Thank you very much.

**Comment by siyi-wind** [comment]
Hi, thanks for the interest. You need to download cardiac MRI data and non-imaging tabular data (phenotypes). The id of used tabular features can be found in this paper's supplementary material https://openaccess.thecvf.com/content/CVPR2023/html/Hager_Best_of_Both_Worlds_Multimodal_Contrastive_Learning_With_Tabular_and_CVPR_2023_paper.html

**Comment by ztt0821** [comment]
Thank you very much for the answer. May I ask do we need to pay for the dataset?

**Comment by siyi-wind** [comment]
Yes, you could ask the UK Biobank office for details (access@ukbiobank.ac.uk)
